In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [3]:
arr1 = np.array([12,34,56])
arr2 = np.array([67,78,89])
print(arr1+arr2)

[ 79 112 145]


In [ ]:
# To find dimension of array use the function
my_arr= np.array([[1,2,3],[4,5,6]])
print(my_arr.ndim)

2


In [11]:
arr3= np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr3.ndim)

3


In [12]:
print(arr3.dtype)

int64


# ones in numpy

In [17]:
#matrix using ones function
one1= np.ones((5,5))
print(one1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
one1= np.ones((5,5),dtype=int)
print(one1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#change ones into bool
one1= np.ones((5,5),dtype=bool)
print(one1)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [21]:
#change ones into string
one1= np.ones((5,5),dtype=str)
print(one1)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


# zeros in numpy


In [22]:
z_ro = np.zeros((4,5))
print(z_ro)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
z_ro = np.zeros((4,5),dtype=float)
print(z_ro)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
z_ro = np.zeros((4,5),dtype=int)
print(z_ro)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
z_ro = np.zeros((4,5),dtype=bool)
print(z_ro)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [26]:
z_ro = np.zeros((4,5),dtype=str)
print(z_ro)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


# empty array

In [28]:
arr4 = np.empty((3,4))
print(arr4)

[[1.06757712e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.50155133e-067 1.72212874e+184 1.85396541e-051]
 [2.69769119e+184 5.98460389e+174 7.79674814e-071 6.05202443e-066]]


# numbers in sequence

In [31]:
s_arr = np.arange(1,14)
print(s_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [34]:
s_arr = np.arange(1,14,3)
print(s_arr)

[ 1  4  7 10 13]


In [39]:
arge= np.linspace(1,4,2)
print(arge)

[1. 4.]


# shaping in an array

In [ ]:
#Convert 1D array to 3D array use function
arr=np.array([[1,2,3,45,34,35,12,3,6,7,1,3,12,13,14,3,4,5]])
arr5= arr.reshape(1,3,6)
print(arr5)

[[[ 1  2  3 45 34 35]
  [12  3  6  7  1  3]
  [12 13 14  3  4  5]]]


In [1]:
#Convert 1D array to 2D array use function
import numpy as np
arr=np.array([1,2,3,45,34,35,12,3,6,7,1,3,12,13,14,3,4,5])
arr5= arr.reshape(3,6)
print(arr5)

[[ 1  2  3 45 34 35]
 [12  3  6  7  1  3]
 [12 13 14  3  4  5]]


In [3]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr.ravel())

[1 2 3 4 5 6 7 8 9 0]


In [4]:
print(arr.flatten())

[1 2 3 4 5 6 7 8 9 0]


In [5]:
print(arr.transpose())

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


# Do Math Functions using NUMPY 

In [6]:
# add tw arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1+arr2)

[ 7  9 11 13]


In [7]:
# sub two arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1-arr2)

[-5 -5 -5 -5]


In [8]:
# multiply tw arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1*arr2)

[ 6 14 24 36]


In [9]:
# div tw arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1/arr2)

[0.16666667 0.28571429 0.375      0.44444444]


In [10]:
# dot mutiply
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1@arr2)

80


In [13]:
#  max number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1.max())
print(arr2.max())

4
9


In [16]:
#  max number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([[6,7,8,9],[7,8,9,12,]])
print(arr1.max(axis=0))
print(arr2.max(axis=1))

4
[ 9 12]


In [17]:
#  min number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(arr1.min())
print(arr2.min())

1
6


In [ ]:
#  min number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([[6,7,8,9],[12,13,14,15]])
print(arr1.min(axis=0))
print(arr2.max(axis=1))

1
[ 9 15]


In [19]:
#  argmax number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.argmax(arr1))
print(np.argmax(arr2))

3
3


In [20]:
#  argmin number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.argmin(arr1))
print(np.argmin(arr2))

0
0


In [21]:
#  sqrt number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[1.         1.41421356 1.73205081 2.        ]
[2.44948974 2.64575131 2.82842712 3.        ]


In [22]:
#  mean number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.mean(arr1))
print(np.mean(arr2))

2.5
7.5


In [ ]:
#  argmax number arrays
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.argmax(arr1))
print(np.argmax(arr2)) 

In [2]:
#  std numbers
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.std(arr1))
print(np.std(arr2))

1.118033988749895
1.118033988749895


In [3]:
#  log numbers
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.log(arr1))
print(np.log(arr2))

[0.         0.69314718 1.09861229 1.38629436]
[1.79175947 1.94591015 2.07944154 2.19722458]


In [4]:
#  log 10 numbers
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.log10(arr1))
print(np.log10(arr2))

[0.         0.30103    0.47712125 0.60205999]
[0.77815125 0.84509804 0.90308999 0.95424251]


In [5]:
#  exp numbers
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.exp(arr1))
print(np.exp(arr2))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 403.42879349 1096.63315843 2980.95798704 8103.08392758]


In [6]:
# arange and reshape
arr1=np.arange(1,101).reshape(10,10)
print(arr1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
#number of rows
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(arr[1])

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
#number of coloumns
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(arr[:1])

[[[1 2 3 4 5]
  [6 7 8 9 0]]]


In [ ]:
#number of coloumns
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(arr[::])

[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[1 2 3 4 5]
  [6 7 8 9 0]]]


In [21]:
#number of coloumns
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(arr[1:1,1:1])

[]


In [2]:
# concatinate 
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 6 7 8 9]


# methods of strings

In [3]:
arr1=np.array("[1,2,3,4]")
arr2=np.array("[6,7,8,9]")
print(np.char.add(arr1,arr2))

[1,2,3,4][6,7,8,9]


In [ ]:
arr1=np.array("['A','B']")
print(np.char.lower(arr1))

['a','b']


In [7]:
arr1=np.array("['a','b']")
print(np.char.upper(arr1))

['A','B']
